### ISSUE TITLE
ESP8266 crashes

### ISSUE THREAD

**Issue by Courty40** [adafruit/Adafruit_HTU21DF_Library#10]
Arduino board: NODEMCU 0.9 esp8266-12 (non E)

Arduino IDE version 1.6.12

- loaded the example and it just crashes, the SparkFun lib works fine so think there's an internal compatibility issue on this one

**Comment by microbuilder** [comment]
Haven't been able to reproduce this ... I'm going to close the issue since it might have been resolved with recent changes, but feel free to reopen!
