### ISSUE TITLE
Please publish an updated tag containing 23176b9

### ISSUE THREAD

**Issue by facchinm** [adafruit/Adafruit_HTU21DF_Library#11]
To avoid any kind of problem with non- AVR boards, please tag the library's `HEAD` in order to include https://github.com/adafruit/Adafruit_HTU21DF_Library/commit/23176b98129e7bbbff4579f2fbbca2a03da55e43

Thanks :smile:

**Comment by facchinm** [comment]
Gentle ping :wink:

**Comment by toddtreece** [comment]
v1.0.1 published: https://github.com/adafruit/Adafruit_HTU21DF_Library/releases/tag/1.0.1
