### ISSUE TITLE
A problem with new version (1.0.1) 

### ISSUE THREAD

**Issue by pilnikov** [adafruit/Adafruit_HTU21DF_Library#12]
The new version of the library (1.0.1) does not work with my Si7021 [.](https://www.aliexpress.com/item-img/I2C-Si7021-Arduino/32684748379.html?spm=2114.10010208.1000017.2.tZlXyU) Whereas 1.0.0 works without problems. 

Problem in method ::begin
`
boolean Adafruit_HTU21DF::begin(void) {
 Wire.begin();
  
  reset();

  Wire.beginTransmission(HTU21DF_I2CADDR);
  Wire.write(HTU21DF_READREG);
  /*  Wire.endTransmission();
  Wire.requestFrom(HTU21DF_I2CADDR, 1);
  Serial.println(Wire.read(), HEX);
  return (Wire.read() == 0x2); // after reset should be 0x2
  */
  return (Wire.endTransmission() == 0);
}
`
 return (Wire.read() == 0x2); // after reset should be 0x2 instead of 0x2 returned `0x3A

I slightly corrected the code as shown above - so everything is OK!

**Comment by ladyada** [comment]
hiya this library isnt for the Si7021, its for the HTUD21 :)
